# default credentials are wallabag:wallabag
version: '3.7'

services:
  wallabag:
    image: wallabag/wallabag
    volumes:
      - ./data:/var/www/wallabag/data
      - ./images:/var/www/wallabag/web/assets/images
    ports:
      - "8085:80"
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=http://localhost:8085

